# Generated by Django 4.1.1 on 2022-10-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services_salon", "0003_alter_servicedetails_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicedetails",
            options={"verbose_name_plural": "Service details"},
        ),
    ]
